dist: bionic
language: python
python:
  - 3.6
  - 3.7

before_install:
  - pip install -U pip
  - pip install -r requirements.txt

install:
  - python3 setup.py install

script:
  - make all-tests

after_success:
  - codecov
