"""This module contains the Image class."""

import configparser
import json
import pathlib
import random
from collections import defaultdict
from operator import itemgetter

import woodblock.datagen
import woodblock.file
import woodblock.fragments
import woodblock.random
from woodblock.errors import ImageConfigError, WoodblockError
from woodblock.scenario import Scenario


class Image:
    """The Image class represents a carving test image.

    An image contains a sequence of `Scenario` instances. An image has a fixed block size. All blocks smaller than the
    block size will be padded with data generated by a configurable data generator.

    Args:
        block_size: Block size of the image.
        padding_generator: A data generator used to generate padding.
    """

    def __init__(self, block_size: int = 512, padding_generator=None):
        self._block_size = block_size
        self._scenarios = []
        if padding_generator is None:
            padding_generator = woodblock.datagen.Random()
        self._generate_padding = padding_generator

    def add(self, scenario):
        """Add a ``Scenario`` to the image."""
        self._scenarios.append(scenario)

    @staticmethod
    def from_config(path: pathlib.Path):
        """Create an Image instance based on a configuration file.

        Args:
            path: The path to the configuration file.
        """
        config = configparser.RawConfigParser()
        with path.open('r') as config_handle:
            try:
                config.read_file(config_handle)
            except configparser.Error as err:
                raise ImageConfigError(str(err)) from err
        general = _parse_general_section(config)
        woodblock.file.corpus(path.absolute().parent / general['corpus'])
        if 'seed' in general:
            woodblock.random.seed(general['seed'])
        num_filler_blocks = (general['min filler blocks'], general['max filler blocks'])
        image = Image()
        for section in config.sections():
            if section != 'general':
                scenario = _parse_scenario_section(
                    section_name=section,
                    section=config[section],
                    num_filler_blocks=num_filler_blocks,
                    block_size=general['block size'],
                )
                image.add(scenario)
        return image

    def write(self, target):
        """Write the image to disk.

        ``target`` may be a path (``str`` or ``pathlib.Path``) or a ``.write()``-supporting file-like
        object. When given a path, the image metadata is also written alongside it: the metadata file is
        ``target`` with the ".json" extension appended, e.g. for "test-image.dd" the image is written to
        "test-image.dd" and the metadata to "test-image.dd.json". When given a file-like object, only the
        image is written -- call :attr:`metadata` yourself if you need the ground truth.

        Args:
            target: The output path or a ``.write()``-supporting file-like object.
        """
        if isinstance(target, (str, pathlib.Path)):
            path = pathlib.Path(target)
            with path.open('wb') as file_handle:
                self.write(file_handle)
            self._write_metadata(path)
            return
        # Reset the padding generator so writing the same image twice yields byte-identical
        # output. User-supplied padding generators may be plain callables without a reset.
        if hasattr(self._generate_padding, 'reset'):
            self._generate_padding.reset()
        for scenario in self._scenarios:
            self._write_scenario(target, scenario)

    @property
    def metadata(self):
        """Return the image metadata."""
        meta = {
            'block_size': self._block_size,
            'seed': woodblock.random.get_seed(),
            'corpus': str(woodblock.file.get_corpus()),
            'scenarios': [s.metadata for s in self._scenarios],
        }
        self._update_metadata_with_image_offsets(meta, self._compute_image_offsets())
        return meta

    def _write_metadata(self, image_path: pathlib.Path):
        image_path = image_path.absolute()
        metadata_path = image_path.with_name(image_path.name + '.json')
        with metadata_path.open('w') as file_handle:
            json.dump(self.metadata, file_handle)

    def _write_scenario(self, image, scenario):
        for fragment in scenario:
            for chunk in fragment:
                image.write(chunk)
            self._pad_fragment(image, fragment.size)

    def _pad_fragment(self, image, fragment_size):
        remainder = fragment_size % self._block_size
        if remainder != 0:
            padding_size = self._block_size - remainder
            image.write(self._generate_padding(padding_size))

    def _compute_image_offsets(self):
        image_offsets = defaultdict(dict)
        current_offset = 0
        for scenario in self._scenarios:
            for frag in scenario:
                frag_meta = frag.metadata
                file_id = frag_meta['file']['id']
                number = frag_meta['fragment']['number']
                frag_size = frag_meta['fragment']['size']
                end_offset = current_offset + frag_size
                if number in image_offsets[file_id]:
                    raise WoodblockError(
                        f'Fragment {number} of file {file_id} is placed more than once in the image. '
                        'The ground truth cannot represent a fragment at more than one location.'
                    )
                image_offsets[file_id][number] = {'start': current_offset, 'end': end_offset}
                current_offset += frag_size
                if current_offset % self._block_size != 0:
                    current_offset += self._block_size - (current_offset % self._block_size)
        return image_offsets

    @staticmethod
    def _update_metadata_with_image_offsets(meta, image_offsets):
        for scenario_meta in meta['scenarios']:
            for file_meta in scenario_meta['files']:
                file_id = file_meta['original']['id']
                for frag_meta in file_meta['fragments']:
                    frag_meta['image_offsets'] = image_offsets[file_id][frag_meta['number']]


def _parse_general_section(config: dict) -> dict:
    if 'general' not in config:
        raise ImageConfigError('Mandatory "general" section is not present.')
    section = config['general']
    if 'corpus' not in section:
        raise ImageConfigError('Mandatory "corpus" key in "general" section is not present.')
    general = {}
    general['corpus'] = section['corpus']
    general['block size'] = int(section.get('block size', 512))
    if 'seed' in section:
        general['seed'] = int(section['seed'])
    general['min filler blocks'] = _get_number_of_blocks(section, 'min') or 1
    general['max filler blocks'] = _get_number_of_blocks(section, 'max') or 10
    _reject_unknown_keys('general', section, _GENERAL_ALLOWED_KEYS)
    return general


def _get_number_of_blocks(section: dict, min_or_max: str):
    if f'{min_or_max} filler blocks' in section:
        blocks = int(section[f'{min_or_max} filler blocks'])
        if blocks < 1:
            raise ImageConfigError(f'Invalid value for "{min_or_max} filler blocks": {blocks}.')
        return blocks
    return None


def _parse_scenario_section(section_name: str, section: dict, num_filler_blocks: tuple, block_size: int):
    try:
        layout = _get_layout_type(section)
    except KeyError as err:
        raise ImageConfigError(f'Section [{section_name}] contains no "layout" key.') from err

    if layout == 'fragment-sequence':
        return _parse_fragment_sequence_layout(section_name, section, num_filler_blocks, block_size)
    if layout == 'intertwine':
        return _parse_intertwine_layout(section_name, section, block_size)
    raise ImageConfigError(f'Unsupported layout type in section [{section_name}]: "{layout}".')


_KEYWORD_LAYOUTS = ('intertwine',)

_GENERAL_ALLOWED_KEYS = frozenset({'corpus', 'block size', 'seed', 'min filler blocks', 'max filler blocks'})
_INTERTWINE_ALLOWED_KEYS = frozenset({'layout', 'num files', 'min frags', 'max frags'})
_FRAGMENT_SEQUENCE_ALLOWED_KEYS = frozenset({'layout', 'min filler blocks', 'max filler blocks'})


def _is_file_definition_key(key: str) -> bool:
    """Return ``True`` for the dynamic ``fileN`` / ``frags fileN`` / ``frags_fileN`` keys."""
    if key.startswith('frags file') or key.startswith('frags_file'):
        return key[len('frags file') :].isdigit()
    if key.startswith('file'):
        return key[len('file') :].isdigit()
    return False


def _reject_unknown_keys(section_name: str, section: dict, allowed: frozenset, dynamic_ok=None):
    """Raise ``ImageConfigError`` for any key not in ``allowed`` and not accepted by ``dynamic_ok``.

    Unknown keys are otherwise ignored silently by the parser, which lets a typo (e.g.
    ``blocksize`` instead of ``block size``) change the output without any error -- dangerous
    for a tool whose images are supposed to be reproducible from their config.
    """
    for key in section:
        if key in allowed:
            continue
        if dynamic_ok is not None and dynamic_ok(key):
            continue
        raise ImageConfigError(f'Unknown key "{key}" in section [{section_name}].')


def _get_layout_type(section: dict) -> str:
    raw = section['layout'].strip()
    layout = raw.lower()
    if layout in _KEYWORD_LAYOUTS:
        return layout
    if _looks_like_fragment_sequence(layout):
        return 'fragment-sequence'
    raise ImageConfigError(
        f'Unsupported layout type: "{raw}". '
        'Use "intertwine" or a comma-separated fragment sequence (e.g. "1.1, 2.3, R, Z").'
    )


def _looks_like_fragment_sequence(layout: str) -> bool:
    if ',' in layout:
        return True
    return layout in ('r', 'z') or '.' in layout or '-' in layout  # nosec


def _parse_intertwine_layout(section_name: str, section: dict, block_size: int):
    _reject_unknown_keys(section_name, section, _INTERTWINE_ALLOWED_KEYS)
    scenario = Scenario(section_name)
    try:
        num_files = section['num files']
    except KeyError as err:
        raise ImageConfigError(
            f'Section [{section_name}] has an intertwined layout but does not specify "num files".'
        ) from err
    num_files = int(num_files)
    min_frags, max_frags = _parse_frags_nums(section_name, section)
    scenario.add(
        woodblock.file.intertwine_randomly(
            number_of_files=num_files, block_size=block_size, min_fragments=min_frags, max_fragments=max_frags
        )
    )
    return scenario


def _parse_fragment_sequence_layout(section_name: str, section: dict, num_filler_blocks: tuple, block_size: int):
    _reject_unknown_keys(section_name, section, _FRAGMENT_SEQUENCE_ALLOWED_KEYS, dynamic_ok=_is_file_definition_key)
    scenario = Scenario(section_name)
    files = dict()
    for key, value in section.items():
        if key.startswith('file'):
            file_number = int(key[4:])
            if file_number in files:
                files[file_number]['path'] = value
            else:
                files[file_number] = {'frags': None, 'path': value}
        elif key.startswith('frags_file') or key.startswith('frags file'):
            file_number = int(key[10:])
            if file_number in files:
                files[file_number]['frags'] = int(value)
            else:
                files[file_number] = {'frags': int(value), 'path': None}
    _assert_each_file_has_a_defined_num_of_frags(files, section_name)
    file_fragments = _create_file_fragments(files)
    layout = _parse_layout_line(section['layout'])

    min_filler_blocks = _get_number_of_blocks(section, 'min') or num_filler_blocks[0]
    max_filler_blocks = _get_number_of_blocks(section, 'max') or num_filler_blocks[1]
    if min_filler_blocks < 1 or max_filler_blocks < 1 or min_filler_blocks > max_filler_blocks:
        raise ImageConfigError(
            f'Invalid min/max number of fillers blocks: min={min_filler_blocks}, max={max_filler_blocks}'
        )
    for fragment in layout:
        if fragment['type'] == 'file':
            scenario.add(file_fragments[fragment['file_num']][fragment['frag_num']])
        elif fragment['type'] == 'random':
            size = _get_filler_fragment_size(min_filler_blocks, max_filler_blocks, block_size)
            scenario.add(woodblock.fragments.RandomDataFragment(size))
        elif fragment['type'] == 'zeroes':
            size = _get_filler_fragment_size(min_filler_blocks, max_filler_blocks, block_size)
            scenario.add(woodblock.fragments.ZeroesFragment(size))
    return scenario


def _parse_frags_nums(section_name: str, section: dict) -> tuple:
    min_frags = _parse_positive_int(section, 'min frags', section_name, default=1)
    max_frags = _parse_positive_int(section, 'max frags', section_name, default=4)
    if min_frags > max_frags:
        raise ImageConfigError(f'"min frags" has to be <= "max frags" in section [{section_name}]')
    return min_frags, max_frags


def _parse_positive_int(section: dict, key: str, section_name: str, default: int) -> int:
    if key not in section:
        return default
    try:
        value = int(section[key])
    except ValueError as err:
        raise ImageConfigError(f'"{key}" has to be an integer > 0 in section [{section_name}]') from err
    if value < 1:
        raise ImageConfigError(f'"{key}" has to be an integer > 0 in section [{section_name}]')
    return value


def _get_filler_fragment_size(min_blocks: int, max_blocks: int, block_size: int) -> int:
    return random.randint(min_blocks, max_blocks) * block_size  # nosec


def _create_file_fragments(files):
    fragments = {}
    for file_num in files:
        num_frags = files[file_num]['frags']
        file_path = files[file_num]['path']
        if file_path is not None:
            if (woodblock.file.get_corpus() / file_path).is_dir():
                frags = woodblock.file.draw_fragmented_files(
                    file_path, number_of_files=1, min_fragments=num_frags, max_fragments=num_frags
                )[0]
            else:
                frags = woodblock.file.File(file_path).fragment_randomly(num_fragments=num_frags)
        else:
            frags = woodblock.file.draw_fragmented_files(
                number_of_files=1, min_fragments=num_frags, max_fragments=num_frags
            )[0]
        fragments[file_num] = {i + 1: f for i, f in enumerate(frags)}
    return fragments


def _assert_each_file_has_a_defined_num_of_frags(files, section):
    for num, file in files.items():
        if file['frags'] is None:
            raise ImageConfigError(f'No "frags file{num} definition is missing in section "[{section}]".')


def _parse_layout_line(line: str) -> list:
    layout = []
    seen_file_fragments = set()
    for token in (x.strip() for x in line.split(',')):
        token = token.lower()
        if token == 'r':  # nosec
            layout.append({'type': 'random'})
        elif token == 'z':  # nosec
            layout.append({'type': 'zeroes'})
        else:
            file_num, frag_num = (int(x) for x in _parse_file_definition(token))
            if (file_num, frag_num) in seen_file_fragments:
                raise ImageConfigError(
                    f'Fragment {frag_num} of file {file_num} is referenced more than once in the layout. '
                    'The ground truth cannot represent a fragment at more than one location.'
                )
            seen_file_fragments.add((file_num, frag_num))
            layout.append({'type': 'file', 'file_num': file_num, 'frag_num': frag_num})
    return layout


def _parse_file_definition(token: str):
    if '.' in token:
        sep = '.'
    elif '-' in token:
        sep = '-'
    else:
        raise ImageConfigError('No valid file/fragment separator found. Use "-" or ".".')
    return token.split(sep)


class ImageLogParser:
    def __init__(self, fp):
        self._log = json.load(fp)

    def get_fragment_order(self):
        fragments = []
        for scenario in self._log['scenarios']:
            for file in scenario['files']:
                fragments.extend(
                    (
                        scenario['name'],
                        file['original']['id'],
                        file['original']['path'],
                        frag['number'],
                        frag['file_offsets']['start'],
                        frag['file_offsets']['end'],
                        frag['image_offsets']['start'],
                        frag['image_offsets']['end'],
                    )
                    for frag in file['fragments']
                )
        return tuple(sorted(fragments, key=itemgetter(6)))
