"""This module contains the Image class."""

import configparser
import itertools
import json
import pathlib
import random
from collections import defaultdict
from operator import itemgetter

import woodblock.datagen
import woodblock.file
import woodblock.fragments
import woodblock.random
from woodblock.errors import ImageConfigError, InvalidFragmentationPointError, WoodblockError
from woodblock.scenario import Scenario


class Image:
    """The Image class represents a carving test image.

    An image contains a sequence of `Scenario` instances. An image has a fixed block size. All blocks smaller than the
    block size will be padded with data generated by a configurable data generator.

    Args:
        block_size: Block size of the image.
        padding_generator: A data generator used to generate padding.
        scenario_gap: Number of blocks of padding to insert between consecutive scenarios.
        target_size: If set, pad the whole image up to this number of blocks.
    """

    def __init__(
        self, block_size: int = 512, padding_generator=None, scenario_gap: int = 0, target_size: int | None = None
    ):
        self._block_size = block_size
        self._scenarios = []
        if padding_generator is None:
            padding_generator = woodblock.datagen.Random()
        self._generate_padding = padding_generator
        self._scenario_gap_bytes = scenario_gap * block_size
        self._target_bytes = target_size * block_size if target_size is not None else None

    def add(self, scenario):
        """Add a ``Scenario`` to the image."""
        self._scenarios.append(scenario)

    @staticmethod
    def from_config(path: pathlib.Path):
        """Create an Image instance based on a configuration file.

        Args:
            path: The path to the configuration file.
        """
        config = configparser.RawConfigParser()
        with path.open('r') as config_handle:
            try:
                config.read_file(config_handle)
            except configparser.Error as err:
                raise ImageConfigError(str(err)) from err
        general = _parse_general_section(config)
        woodblock.file.corpus(path.absolute().parent / general['corpus'])
        if 'seed' in general:
            woodblock.random.seed(general['seed'])
        num_filler_blocks = (general['min filler blocks'], general['max filler blocks'])
        image = Image(
            block_size=general['block size'],
            scenario_gap=general['scenario gap'],
            target_size=general.get('image size'),
        )
        for section in config.sections():
            if section != 'general':
                scenario = _parse_scenario_section(
                    section_name=section,
                    section=config[section],
                    num_filler_blocks=num_filler_blocks,
                    block_size=general['block size'],
                )
                image.add(scenario)
        if image._target_bytes is not None and image._target_bytes < image._content_size():
            raise ImageConfigError(
                f'"image size" ({general["image size"]} blocks) is smaller than the image content '
                f'({image._content_size() // general["block size"]} blocks).'
            )
        return image

    def write(self, target):
        """Write the image to disk.

        ``target`` may be a path (``str`` or ``pathlib.Path``) or a ``.write()``-supporting file-like
        object. When given a path, the image metadata is also written alongside it: the metadata file is
        ``target`` with the ".json" extension appended, e.g. for "test-image.dd" the image is written to
        "test-image.dd" and the metadata to "test-image.dd.json". When given a file-like object, only the
        image is written -- call :attr:`metadata` yourself if you need the ground truth.

        Args:
            target: The output path or a ``.write()``-supporting file-like object.
        """
        if isinstance(target, (str, pathlib.Path)):
            path = pathlib.Path(target)
            with path.open('wb') as file_handle:
                self.write(file_handle)
            self._write_metadata(path)
            return
        # Reset the padding generator so writing the same image twice yields byte-identical
        # output. User-supplied padding generators may be plain callables without a reset.
        if hasattr(self._generate_padding, 'reset'):
            self._generate_padding.reset()
        for scenario, gap in self._scenarios_with_trailing_gaps():
            self._write_scenario(target, scenario)
            if gap:
                target.write(self._generate_padding(gap))
        if self._target_bytes is not None:
            content_size = self._content_size()
            if self._target_bytes < content_size:
                raise WoodblockError(
                    f'Target image size ({self._target_bytes} bytes) is smaller than the image '
                    f'content ({content_size} bytes).'
                )
            if self._target_bytes > content_size:
                target.write(self._generate_padding(self._target_bytes - content_size))

    @property
    def metadata(self):
        """Return the image metadata."""
        meta = {
            'block_size': self._block_size,
            'seed': woodblock.random.get_seed(),
            'corpus': str(woodblock.file.get_corpus()),
            'scenarios': [s.metadata for s in self._scenarios],
        }
        image_offsets, _ = self._compute_image_offsets()
        self._update_metadata_with_image_offsets(meta, image_offsets)
        return meta

    def _write_metadata(self, image_path: pathlib.Path):
        image_path = image_path.absolute()
        metadata_path = image_path.with_name(image_path.name + '.json')
        with metadata_path.open('w') as file_handle:
            json.dump(self.metadata, file_handle)

    def _scenarios_with_trailing_gaps(self):
        """Yield ``(scenario, gap_bytes)`` pairs.

        The inter-scenario gap is applied after every scenario except the last one. Both the write
        path and the offset computation iterate through this helper so they can never disagree on
        where (and how much) padding goes between scenarios.
        """
        last = len(self._scenarios) - 1
        for index, scenario in enumerate(self._scenarios):
            yield scenario, (0 if index == last else self._scenario_gap_bytes)

    def _content_size(self):
        """Return the size (in bytes) of the image content, i.e. all fragments plus inter-scenario gaps."""
        return self._compute_image_offsets()[1]

    def _write_scenario(self, image, scenario):
        for fragment in scenario:
            for chunk in fragment:
                image.write(chunk)
            self._pad_fragment(image, fragment.size)

    def _pad_fragment(self, image, fragment_size):
        remainder = fragment_size % self._block_size
        if remainder != 0:
            padding_size = self._block_size - remainder
            image.write(self._generate_padding(padding_size))

    def _compute_image_offsets(self):
        image_offsets = defaultdict(dict)
        current_offset = 0
        for scenario, gap in self._scenarios_with_trailing_gaps():
            for frag in scenario:
                frag_meta = frag.metadata
                file_id = frag_meta['file']['id']
                number = frag_meta['fragment']['number']
                frag_size = frag_meta['fragment']['size']
                end_offset = current_offset + frag_size
                if number in image_offsets[file_id]:
                    raise WoodblockError(
                        f'Fragment {number} of file {file_id} is placed more than once in the image. '
                        'The ground truth cannot represent a fragment at more than one location.'
                    )
                image_offsets[file_id][number] = {'start': current_offset, 'end': end_offset}
                current_offset += frag_size
                if current_offset % self._block_size != 0:
                    current_offset += self._block_size - (current_offset % self._block_size)
            current_offset += gap
        return image_offsets, current_offset

    @staticmethod
    def _update_metadata_with_image_offsets(meta, image_offsets):
        for scenario_meta in meta['scenarios']:
            for file_meta in scenario_meta['files']:
                file_id = file_meta['original']['id']
                for frag_meta in file_meta['fragments']:
                    frag_meta['image_offsets'] = image_offsets[file_id][frag_meta['number']]


def _parse_general_section(config: dict) -> dict:
    if 'general' not in config:
        raise ImageConfigError('Mandatory "general" section is not present.')
    section = config['general']
    if 'corpus' not in section:
        raise ImageConfigError('Mandatory "corpus" key in "general" section is not present.')
    general = {}
    general['corpus'] = section['corpus']
    general['block size'] = int(section.get('block size', 512))
    if 'seed' in section:
        general['seed'] = int(section['seed'])
    general['min filler blocks'] = _get_number_of_blocks(section, 'min') or 1
    general['max filler blocks'] = _get_number_of_blocks(section, 'max') or 10
    general['scenario gap'] = _parse_scenario_gap(section)
    image_size = _parse_image_size(section)
    if image_size is not None:
        general['image size'] = image_size
    _reject_unknown_keys('general', section, _GENERAL_ALLOWED_KEYS)
    return general


def _parse_scenario_gap(section: dict) -> int:
    try:
        gap = int(section.get('scenario gap', 0))
    except ValueError as err:
        raise ImageConfigError('"scenario gap" has to be an integer >= 0.') from err
    if gap < 0:
        raise ImageConfigError(f'Invalid value for "scenario gap": {gap}. It has to be >= 0.')
    return gap


def _parse_image_size(section: dict):
    if 'image size' not in section:
        return None
    try:
        size = int(section['image size'])
    except ValueError as err:
        raise ImageConfigError('"image size" has to be an integer >= 1.') from err
    if size < 1:
        raise ImageConfigError(f'Invalid value for "image size": {size}. It has to be >= 1.')
    return size


def _get_number_of_blocks(section: dict, min_or_max: str):
    if f'{min_or_max} filler blocks' in section:
        blocks = int(section[f'{min_or_max} filler blocks'])
        if blocks < 1:
            raise ImageConfigError(f'Invalid value for "{min_or_max} filler blocks": {blocks}.')
        return blocks
    return None


def _parse_scenario_section(section_name: str, section: dict, num_filler_blocks: tuple, block_size: int):
    try:
        layout = _get_layout_type(section)
    except KeyError as err:
        raise ImageConfigError(f'Section [{section_name}] contains no "layout" key.') from err

    if layout == 'fragment-sequence':
        return _parse_fragment_sequence_layout(section_name, section, num_filler_blocks, block_size)
    if layout == 'intertwine':
        return _parse_intertwine_layout(section_name, section, block_size)
    raise ImageConfigError(f'Unsupported layout type in section [{section_name}]: "{layout}".')


_KEYWORD_LAYOUTS = ('intertwine',)

_GENERAL_ALLOWED_KEYS = frozenset(
    {'corpus', 'block size', 'seed', 'min filler blocks', 'max filler blocks', 'scenario gap', 'image size'}
)
_INTERTWINE_ALLOWED_KEYS = frozenset({'layout', 'num files', 'min frags', 'max frags'})
_FRAGMENT_SEQUENCE_ALLOWED_KEYS = frozenset({'layout', 'min filler blocks', 'max filler blocks'})


def _is_file_definition_key(key: str) -> bool:
    """Return ``True`` for the dynamic ``fileN`` / ``frags fileN`` / ``sizes fileN`` keys.

    Both the space- and underscore-separated spellings (e.g. ``frags file1`` and ``frags_file1``)
    are accepted.
    """
    if key.startswith('frags file') or key.startswith('frags_file'):
        return key[len('frags file') :].isdigit()
    if key.startswith('sizes file') or key.startswith('sizes_file'):
        return key[len('sizes file') :].isdigit()
    if key.startswith('file'):
        return key[len('file') :].isdigit()
    return False


def _reject_unknown_keys(section_name: str, section: dict, allowed: frozenset, dynamic_ok=None):
    """Raise ``ImageConfigError`` for any key not in ``allowed`` and not accepted by ``dynamic_ok``.

    Unknown keys are otherwise ignored silently by the parser, which lets a typo (e.g.
    ``blocksize`` instead of ``block size``) change the output without any error -- dangerous
    for a tool whose images are supposed to be reproducible from their config.
    """
    for key in section:
        if key in allowed:
            continue
        if dynamic_ok is not None and dynamic_ok(key):
            continue
        raise ImageConfigError(f'Unknown key "{key}" in section [{section_name}].')


def _get_layout_type(section: dict) -> str:
    raw = section['layout'].strip()
    layout = raw.lower()
    if layout in _KEYWORD_LAYOUTS:
        return layout
    if _looks_like_fragment_sequence(layout):
        return 'fragment-sequence'
    raise ImageConfigError(
        f'Unsupported layout type: "{raw}". '
        'Use "intertwine" or a comma-separated fragment sequence (e.g. "1.1, 2.3, R, Z").'
    )


def _looks_like_fragment_sequence(layout: str) -> bool:
    if ',' in layout:
        return True
    kind = layout.partition(':')[0]
    return kind in ('r', 'z') or '.' in layout or '-' in layout  # nosec


def _parse_intertwine_layout(section_name: str, section: dict, block_size: int):
    _reject_unknown_keys(section_name, section, _INTERTWINE_ALLOWED_KEYS)
    scenario = Scenario(section_name)
    try:
        num_files = section['num files']
    except KeyError as err:
        raise ImageConfigError(
            f'Section [{section_name}] has an intertwined layout but does not specify "num files".'
        ) from err
    num_files = int(num_files)
    min_frags, max_frags = _parse_frags_nums(section_name, section)
    scenario.add(
        woodblock.file.intertwine_randomly(
            number_of_files=num_files, block_size=block_size, min_fragments=min_frags, max_fragments=max_frags
        )
    )
    return scenario


def _parse_fragment_sequence_layout(section_name: str, section: dict, num_filler_blocks: tuple, block_size: int):
    _reject_unknown_keys(section_name, section, _FRAGMENT_SEQUENCE_ALLOWED_KEYS, dynamic_ok=_is_file_definition_key)
    scenario = Scenario(section_name)
    files = dict()
    for key, value in section.items():
        if key.startswith('sizes file') or key.startswith('sizes_file'):
            file_number = int(key[10:])
            files.setdefault(file_number, {'frags': None, 'path': None, 'sizes': None})
            files[file_number]['sizes'] = _parse_sizes_value(key, value)
        elif key.startswith('frags_file') or key.startswith('frags file'):
            file_number = int(key[10:])
            files.setdefault(file_number, {'frags': None, 'path': None, 'sizes': None})
            files[file_number]['frags'] = int(value)
        elif key.startswith('file'):
            file_number = int(key[4:])
            files.setdefault(file_number, {'frags': None, 'path': None, 'sizes': None})
            files[file_number]['path'] = value
    _assert_each_file_has_a_defined_num_of_frags(files, section_name)
    file_fragments = _create_file_fragments(files, block_size)
    layout = _parse_layout_line(section['layout'])

    min_filler_blocks = _get_number_of_blocks(section, 'min') or num_filler_blocks[0]
    max_filler_blocks = _get_number_of_blocks(section, 'max') or num_filler_blocks[1]
    if min_filler_blocks < 1 or max_filler_blocks < 1 or min_filler_blocks > max_filler_blocks:
        raise ImageConfigError(
            f'Invalid min/max number of fillers blocks: min={min_filler_blocks}, max={max_filler_blocks}'
        )
    for fragment in layout:
        if fragment['type'] == 'file':
            scenario.add(file_fragments[fragment['file_num']][fragment['frag_num']])
        elif fragment['type'] in ('random', 'zeroes'):
            if fragment['size_blocks'] is not None:
                size = fragment['size_blocks'] * block_size
            else:
                size = _get_filler_fragment_size(min_filler_blocks, max_filler_blocks, block_size)
            filler_cls = (
                woodblock.fragments.RandomDataFragment
                if fragment['type'] == 'random'
                else woodblock.fragments.ZeroesFragment
            )
            scenario.add(filler_cls(size))
    return scenario


def _parse_sizes_value(key: str, value: str) -> list:
    try:
        return [int(x) for x in value.split(',')]
    except ValueError as err:
        raise ImageConfigError(f'"{key}" has to be a comma-separated list of integers.') from err


def _parse_frags_nums(section_name: str, section: dict) -> tuple:
    min_frags = _parse_positive_int(section, 'min frags', section_name, default=1)
    max_frags = _parse_positive_int(section, 'max frags', section_name, default=4)
    if min_frags > max_frags:
        raise ImageConfigError(f'"min frags" has to be <= "max frags" in section [{section_name}]')
    return min_frags, max_frags


def _parse_positive_int(section: dict, key: str, section_name: str, default: int) -> int:
    if key not in section:
        return default
    try:
        value = int(section[key])
    except ValueError as err:
        raise ImageConfigError(f'"{key}" has to be an integer > 0 in section [{section_name}]') from err
    if value < 1:
        raise ImageConfigError(f'"{key}" has to be an integer > 0 in section [{section_name}]')
    return value


def _get_filler_fragment_size(min_blocks: int, max_blocks: int, block_size: int) -> int:
    return random.randint(min_blocks, max_blocks) * block_size  # nosec


def _create_file_fragments(files, block_size):
    fragments = {}
    for file_num in files:
        num_frags = files[file_num]['frags']
        file_path = files[file_num]['path']
        sizes = files[file_num]['sizes']
        if sizes is not None:
            frags = _fragment_with_explicit_sizes(file_num, file_path, sizes, num_frags, block_size)
        elif file_path is not None:
            if (woodblock.file.get_corpus() / file_path).is_dir():
                frags = woodblock.file.draw_fragmented_files(
                    file_path,
                    number_of_files=1,
                    block_size=block_size,
                    min_fragments=num_frags,
                    max_fragments=num_frags,
                )[0]
            else:
                frags = woodblock.file.File(file_path).fragment_randomly(num_fragments=num_frags, block_size=block_size)
        else:
            frags = woodblock.file.draw_fragmented_files(
                number_of_files=1, block_size=block_size, min_fragments=num_frags, max_fragments=num_frags
            )[0]
        fragments[file_num] = {i + 1: f for i, f in enumerate(frags)}
    return fragments


def _fragment_with_explicit_sizes(file_num, file_path, sizes, num_frags, block_size):
    if any(not isinstance(size, int) or size < 1 for size in sizes):
        raise ImageConfigError(f'All values of "sizes file{file_num}" have to be integers >= 1.')
    if num_frags is not None and num_frags != len(sizes):
        raise ImageConfigError(
            f'"frags file{file_num}" ({num_frags}) does not match the number of "sizes file{file_num}" ({len(sizes)}).'
        )
    file = _select_file_for_explicit_sizes(file_path, sizes, block_size)
    points = list(itertools.accumulate(sizes[:-1]))
    file_tail = file.max_fragments(block_size) - (points[-1] if points else 0)
    if sizes[-1] != file_tail:
        raise ImageConfigError(
            f'The last value of "sizes file{file_num}" ({sizes[-1]}) does not match the remaining file '
            f'tail ({file_tail} blocks).'
        )
    try:
        return file.fragment(points, block_size)
    except InvalidFragmentationPointError as err:
        raise ImageConfigError(f'Invalid "sizes file{file_num}": {err}') from err


def _select_file_for_explicit_sizes(file_path, sizes, block_size):
    min_size = sum(sizes) * block_size
    if file_path is None:
        return woodblock.file.draw_files(number_of_files=1, min_size=min_size)[0]
    if (woodblock.file.get_corpus() / file_path).is_dir():
        return woodblock.file.draw_files(file_path, number_of_files=1, min_size=min_size)[0]
    return woodblock.file.File(file_path)


def _assert_each_file_has_a_defined_num_of_frags(files, section):
    for num, file in files.items():
        if file['frags'] is None and file['sizes'] is None:
            raise ImageConfigError(
                f'Neither "frags file{num}" nor "sizes file{num}" is defined in section "[{section}]".'
            )


def _parse_layout_line(line: str) -> list:
    layout = []
    seen_file_fragments = set()
    for token in (x.strip() for x in line.split(',')):
        token = token.lower()
        kind, has_size, arg = token.partition(':')
        if kind == 'r':  # nosec
            layout.append({'type': 'random', 'size_blocks': _parse_filler_size(arg, has_size)})
        elif kind == 'z':  # nosec
            layout.append({'type': 'zeroes', 'size_blocks': _parse_filler_size(arg, has_size)})
        else:
            file_num, frag_num = (int(x) for x in _parse_file_definition(token))
            if (file_num, frag_num) in seen_file_fragments:
                raise ImageConfigError(
                    f'Fragment {frag_num} of file {file_num} is referenced more than once in the layout. '
                    'The ground truth cannot represent a fragment at more than one location.'
                )
            seen_file_fragments.add((file_num, frag_num))
            layout.append({'type': 'file', 'file_num': file_num, 'frag_num': frag_num})
    return layout


def _parse_filler_size(arg: str, has_size: str):
    """Parse the optional ``:N`` block-size suffix of a filler token (e.g. ``R:8``)."""
    if not has_size:
        return None
    try:
        size = int(arg)
    except ValueError as err:
        raise ImageConfigError(f'Invalid filler size "{arg}". It has to be an integer >= 1.') from err
    if size < 1:
        raise ImageConfigError(f'Invalid filler size: {size}. It has to be an integer >= 1.')
    return size


def _parse_file_definition(token: str):
    if '.' in token:
        sep = '.'
    elif '-' in token:
        sep = '-'
    else:
        raise ImageConfigError('No valid file/fragment separator found. Use "-" or ".".')
    return token.split(sep)


class ImageLogParser:
    def __init__(self, fp):
        self._log = json.load(fp)

    def get_fragment_order(self):
        fragments = []
        for scenario in self._log['scenarios']:
            for file in scenario['files']:
                fragments.extend(
                    (
                        scenario['name'],
                        file['original']['id'],
                        file['original']['path'],
                        frag['number'],
                        frag['file_offsets']['start'],
                        frag['file_offsets']['end'],
                        frag['image_offsets']['start'],
                        frag['image_offsets']['end'],
                    )
                    for frag in file['fragments']
                )
        return tuple(sorted(fragments, key=itemgetter(6)))
